export { EventEmitter } from 'https://deno.land/std@0.132.0/node/events.ts'
export { deepMerge } from 'https://deno.land/std@0.132.0/collections/deep_merge.ts'
export { Collection } from 'https://esm.sh/@discordjs/collection@0.6.0'
export * from 'https://deno.land/x/itchatjs_utils/mod.ts'
export * from 'https://deno.land/x/itchatjs_rest/mod.ts'